export const introductionText = "Welcome to a world where curiosity meets endless possibilities. Dive in and explore the extraordinary – a click away from wonders!"

export const blogCategories = [
  "Travel",
  "Food and Cooking",
  "Lifestyle",
  "Fashion",
  "Beauty and Skincare",
  "Personal Development",
  "Health and Wellness",
  "Fitness",
  "Parenting",
  "Technology",
  "Gaming",
  "Home Decor",
  "DIY and Crafts",
  "Photography",
  "Finance and Budgeting",
  "Career and Professional Development",
  "Education",
  "Book Reviews",
  "Movie and TV Reviews",
  "Music",
  "Art and Design",
  "Mental Health",
  "Sustainability and Eco-friendly Living",
  "Outdoor Activities",
  "Pet Care",
  "Science",
  "History",
  "Social Issues and Activism",
  "Humor and Satire",
  "Personal Finance",
  "Gardening",
  "Car Enthusiasts",
  "Sports",
  "Personal Stories and Memoirs",
  "Inspirational and Motivational",
  "Product Reviews",
  "Relationship and Dating Advice",
  "Wedding Planning",
  "Business and Entrepreneurship",
  "Spirituality and Mindfulness"
];